Fixes e2e test failure
aws-controllers-k8s/memorydb-controller pull request #33
Opened 2022-11-18 22:57 UTC by kyriechen96

Issue #, if available:
Fixes e2e test failure in #30 
Description of changes:
Changes failed test file.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-21 22:04 UTC, kyriechen96 commented
/retest

2022-11-22 04:43 UTC, kyriechen96 commented
/retest

2022-11-23 21:23 UTC, RedbackThomson requested changes
Please delete the empty `abc.json` file

2022-11-23 21:59 UTC, kyriechen96 commented
> Please delete the empty `abc.json` file
Done

2022-11-23 22:03 UTC, kyriechen96 commented
Currently removes the failed step "PERFORM_SCALE_UP_AND_SCALE_IN" in cluster_memory_validations.yaml

Going to make PR #30 work and add new feather first, and then come back to deal this failed part next week.

2022-11-24 00:21 UTC, jljaco commented
/lgtm

2022-11-24 00:22 UTC, jljaco approved these changes
LGTM -- @kyriechen96 to return to a fix for this commented-out test next week

2022-11-24 04:28 UTC, A-Hilaly commented
Fair enough.
/lgtm

2022-11-24 04:29 UTC, merged